version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: master
  labels:
  - dependencies
  versioning-strategy: increase
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: elliptic
    versions:
    - 6.5.4
  - dependency-name: "@types/sinon"
    versions:
    - 9.0.10
  - dependency-name: typescript
    versions:
    - 4.1.3
  - dependency-name: "@babel/helper-get-function-arity"
    versions:
    - 7.12.10
  - dependency-name: graceful-fs
    versions:
    - 4.2.4
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: has-symbols
    versions:
    - 1.0.1
