language : node_js
node_js :
 - stable
install:
 - npm install
script:
 - npm run lint
 - npm run cover

after_script: node_modules/nyc/bin/nyc.js  report --reporter=text-lcov | node_modules/coveralls/bin/coveralls.js 
