language : node_js
node_js :
 - stable
install:
 - npm install
script:
 - npm run lint
 - npm run cover
deploy:
  provider: npm
  edge: true
  email: "g0r0kent0@gmail.com"
  api_key: $NPM_TOKEN
  on:
    branch: master
after_script: node_modules/nyc/bin/nyc.js  report --reporter=text-lcov | node_modules/coveralls/bin/coveralls.js 
